// import './range.js'
// import './modal-saved.js'
// import './registration.js'
// import './mobile-menu.js'
// import './login.js'
// import './fogot-pass.js'
import './play-video.js'
import './show-image.js'